# Generated by Django 5.1.1 on 2024-09-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_verification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification_token',
        ),
    ]
