# Generated by Django 5.1.1 on 2024-09-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
